export const StaticData = {
    Meta_title: " RESTAURANT Demo - Online Restaurant View",
    Meta_description: "RESTAURANT LOCATION",
    locator_breadcrumb: "Restaurant",
    FindLocationtext: "Find Restaurant Location",
    Usemylocation: "Use My Location",
    Search: "Search",
    Brandname: "Restaurant",
    miles: "miles",
    tempClosed: "Temporarily Closed",
    StoreDetailbtn: "View More Data ",
    Storehighlight: "Store Highlights",
    Days: "Days",
    Hours: "Hours",
    Minutes: "Minutes",
    Seconds: "Seconds",
    FAQheading: "How can we help ?",
    getDirection: " Get Directions",
    AllRegion: "All Regions of",
    NearStoretext: "Near By Restaurant",
    AllLocationtext: "View All Location",
    PagenotFound: "404 - Page Not Found",
    cantfind_page: "We're really sorry, we can't find the place you're looking for",
    Youcouldtry: "You could try",
    Previuspage: "Going back to the previous page",
    homePage: "Going back to the homepage",
    StoreFinder: "Store Finder",
    FAQs: "FAQs",
    DownloadApp: "Download Our App",
    cookie: "cookies policy",
    Closed: "Closed",
    DayofWeek: "Day of the Week",
    Reopenmessage: "Message - The store is temporarily closed. It will reopen at",
    Address: "Address",
    Telephone: "Telephone",
    Holdiay: "Holiday Hours",
}